[package]
name = "skump"
version = "0.1.0"
authors = ["Erik Moldtmann <erik.moldtmann@altow.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
rusqlite = "0.24.0"
anyhow = "1.0.32"